### ISSUE TITLE
SEBAL did not run line 2 fully

### ISSUE THREAD

**Issue by atahanEvcen** [spareeth/PySEBAL_dev#2]
**
Hi @spareeth,

PySEBAL ran the test_data without any problems. But when I run PySEBAL with my own data, I get the same error as @janardanroy in the "log" file. I made the necessary changes. My file path in Run_py.3 does not seem to be a problem. As you can see, it produces a few outputs, but does not run after the "Meteo Part1" section. (I got my Meteo_Input data from Eddy Covariance Flux Tower)
What should I do for this error? I would be glad if you help.
Have a nice day.

**
![hata1](https://user-images.githubusercontent.com/74354487/153411945-0ea481bb-5937-4256-9426-1c6927d79dbb.PNG)
![meteo_input](https://user-images.githubusercontent.com/74354487/153411951-c444ee82-5de2-4af8-859c-5597e092d68d.PNG)

**Comment by atahanEvcen** [comment]
Hello @spareeth,
If I can't get an answer to my question for 15 days, why does such a platform exist?

**Comment by spareeth** [comment]
@cartographer16 Most of these libraries are maintained voluntarily, contributors have other full time jobs.
You could also send "Gentle reminders" in a weeks time to get attention.

Your issue is similar to other issue reported.

If the test data ran with out issues, then that means this happens due to your excel sheet entries, mainly path related.
Could you recheck the excel sheet entries?

In Sheet 1, check if the paths exists.
I understand, you have used numeric values for meteo so thats fine.
In soil , is it also numeric?
Also in sheet 4 where Landsat the landsat name should be the prefix before the band numbers.

https://pysebal-doc.readthedocs.io/en/version3.7.3/
https://pysebal-doc.readthedocs.io/en/version3.7.3/run.html#input-data-preparation

If it still doesnt work, I can have look at your excel sheet.

**Comment by atahanEvcen** [comment]
https://drive.google.com/drive/folders/1VDvLTrBjkTW2dlFhn35HFKb7frOrDUmk?usp=sharing I've done all the checks again. I made the same mistake again.  I would appreciate it if you could help. @spareeth

**Comment by atahanEvcen** [comment]
@spareeth :)

**Comment by spareeth** [comment]
I tested your data.
For PySEBAL the DEM data should be LatLong WGS84 (EPSG:4326), now the dem is in utm. Convert dem to EPSG:4326
I saw that you have also edited the pysebal_py3.py, especially commented some lines: 696-701.

I suggest you download the pysebal_py3.py from https://github.com/spareeth/PySEBAL_dev , try it with DEM in EPSG:4326 and the script should run.

**Comment by spareeth** [comment]
The issue was with the input data preparation
